version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    hostname: '127.0.0.1'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8000:80'
      - '4443:443'
      - '2222:22'