version: '3'
services:
  gogs:
    image: gogs/gogs
    container_name: gogs
    ports:
      - '10080:3000'
      - '10022:22'
    volumes:
      - gogs-data:/data
volumes:
  gogs-data:
networks:
  default:
    external:
      name: docker-network