version: '3'
services:
  gogs:
    image: gogs/gogs
    ports:
      - '10080:3000'
      - '10022:22'
    volumes:
      - gogs-data:/data
    links:
      - mysql

  mysql:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gogs

volumes:
  gogs-data: {}
  mysql-data: {}
  