version: '3'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_PASSWORD: password
networks:
  default:
    external:
      name: docker-network
