version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - '25565:25565'
    volumes:
      - 'mc:/data'
    environment:
      EULA: 'TRUE'
      CONSOLE: 'false'
      ENABLE_RCON: 'true'
      RCON_PASSWORD: 'testing'
      RCON_PORT: 28016
    restart: always
  rcon:
    image: itzg/rcon
    container_name: rcon
    ports:
      - '4326:4326'
      - '4327:4327'
    volumes:
      - 'rcon:/opt/rcon-web-admin/db'
volumes:
  mc:
  rcon: