version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    command: server /data
volumes:
  minio-data:
networks:
  default:
    external:
      name: docker-network
      
